language: rust
os:
    - linux
    - osx
env:
    global:
        - LD_LIBRARY_PATH: /usr/local/lib
before_script:
    - rustc -v
    - cargo -V
script:
    - cargo build -v
    - cargo test -v
    - cd examples/image_iter/
    - cargo build -v
