language: rust
rust:
  - nightly
  - 1.0.0-beta.4
before_install:
  - sudo add-apt-repository ppa:team-xbmc/ppa -y
  - sudo apt-get update -qq
install:
  - sudo apt-get install libsdl2-dev
script:
  - cargo test -v
  - cargo doc -v
