[package]

name = "piston2d-gfx_graphics"
version = "0.31.2"
authors = ["bvssvni <bvssvni@gmail.com>"]
keywords = ["graphics", "2d", "gfx", "piston"]
description = "A Gfx 2D back-end for the Piston game engine"
license = "MIT"
readme = "README.md"
repository = "https://github.com/PistonDevelopers/gfx_graphics.git"
homepage = "https://github.com/PistonDevelopers/gfx_graphics"


[lib]

name = "gfx_graphics"


[dependencies]
rusttype = "0.2.1"
gfx = "0.12.0"
draw_state = "0.6.0"
piston-shaders_graphics2d = "0.2.1"
piston-gfx_texture = "0.17.0"
piston2d-graphics = "0.17.0"
shader_version = "0.2.1"

[dev-dependencies]
pistoncore-glutin_window = "0.28.0"
piston = "0.24.0"
find_folder = "0.3.0"
gfx_device_gl = "0.11.0"
gfx_core = "0.4.0"
