[package]

name = "piston2d-gfx_graphics"
version = "0.17.0"
authors = ["bvssvni <bvssvni@gmail.com>"]
keywords = ["graphics", "2d", "gfx", "piston"]
description = "A Gfx 2D back-end for the Piston game engine"
license = "MIT"
readme = "README.md"
repository = "https://github.com/PistonDevelopers/gfx_graphics.git"
homepage = "https://github.com/PistonDevelopers/gfx_graphics"


[lib]

name = "gfx_graphics"


[dependencies]
freetype-rs = "0.4.0"
gfx = "0.8.0"
piston-shaders_graphics2d = "0.1.0"
piston-gfx_texture = "0.7.0"
piston2d-graphics = "0.13.0"

