[package]

name = "gfx_graphics"
version = "0.0.0"
authors = ["bvssvni <bvssvni@gmail.com>"]
tags = []

[lib]

name = "gfx_graphics"
path = "src/lib.rs"

[dependencies.gfx]

git = "https://github.com/gfx-rs/gfx-rs"

[dependencies.gfx_macros]

git = "https://github.com/gfx-rs/gfx-rs"

[dependencies.graphics]

git = "https://github.com/pistondevelopers/graphics"

[dependencies.image]

git = "https://github.com/pistondevelopers/image"
