[package]

name = "piston2d-gfx_graphics"
version = "0.22.0"
authors = ["bvssvni <bvssvni@gmail.com>"]
keywords = ["graphics", "2d", "gfx", "piston"]
description = "A Gfx 2D back-end for the Piston game engine"
license = "MIT"
readme = "README.md"
repository = "https://github.com/PistonDevelopers/gfx_graphics.git"
homepage = "https://github.com/PistonDevelopers/gfx_graphics"


[lib]

name = "gfx_graphics"


[dependencies]
freetype-rs = "0.5.0"
gfx = "0.9.1"
piston-shaders_graphics2d = "0.1.0"
piston-gfx_texture = "0.9.0"
piston2d-graphics = "0.15.0"
shader_version = "0.2.1"

[dev-dependencies]
pistoncore-glutin_window = "0.21.0"
piston = "0.18.0"
find_folder = "0.3.0"
gfx_device_gl = "0.8.2"
