[package]

name = "piston2d-gfx_graphics"
version = "0.1.11"
authors = ["bvssvni <bvssvni@gmail.com>"]
keywords = ["graphics", "2d", "gfx", "piston"]
description = "A Gfx 2D back-end for the Piston game engine"
license = "MIT"
readme = "README.md"
repository = "https://github.com/PistonDevelopers/gfx_graphics.git"
homepage = "https://github.com/PistonDevelopers/gfx_graphics"

[lib]

name = "gfx_graphics"

[dependencies.piston2d-graphics]
git = "https://github.com/pistondevelopers/graphics"
#version = "0.0.6"

[dependencies.piston-gfx_texture]
git = "https://github.com/pistondevelopers/gfx_texture"
#version = "0.0.0"

[dependencies.gfx]
git = "https://github.com/gfx-rs/gfx-rs"
#version = "0.2.0"

[dependencies.gfx_macros]
git = "https://github.com/gfx-rs/gfx_macros"
#version = "0.1.7"

[dependencies.freetype-rs]
git = "https://github.com/PistonDevelopers/freetype-rs.git"
#version = "0.0.6"

[dev-dependencies.piston]
git = "https://github.com/pistondevelopers/piston"
#version = "0.0.0"

[dev-dependencies.pistoncore-sdl2_window]
git = "https://github.com/pistondevelopers/sdl2_window"
#version = "0.0.0"

[dev-dependencies.gfx_device_gl]
git = "https://github.com/gfx-rs/gfx_device_gl"
#version = "0.2.0"

[features]

default = ["image_png"]
image_gif = ["piston-gfx_texture/image/gif"]
image_jpeg = ["piston-gfx_texture/image/jpeg"]
image_png = ["piston-gfx_texture/image/png"]
image_ppm = ["piston-gfx_texture/image/ppm"]
image_tga = ["piston-gfx_texture/image/tga"]
image_tiff = ["piston-gfx_texture/image/tiff"]
image_webp = ["piston-gfx_texture/image/webp"]
